name: ProgressumConsulting
favicon: null
layout_spectrum: 0.7253581646364182
typography_spectrum: 0.536351851420477
title: ProgressumConsulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62020705-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8606662238016725
  lightness: 0.9301257741171867
  saturation: 0.22671585204079747
  rhythmicContrast: 0.02415147447027266
purpose: []
