name: ProgressumConsulting
favicon: null
layout_spectrum: 0.74682
typography_spectrum: 0.65426
title: ProgressumConsulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-62020705-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005e00'
    - '#3f8640'
    - '#92278f'
    - '#ae5dac'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
